### PR TITLE
PHP 7.2 support

### PR DESCRIPTION
**Pull request by zYn**
Fixed the invalid class name from "Object" to "BaseObject"
Updated composer files to fix guzzle problem with php 7.2

### CODE REVIEW

**Comment by hugovk** [comment]
Thank you for the PR. 

This has broken the build for PHP 5.6 and 7.0.

But I think it's probably fine to drop them as they're EOL in 2 months and 1 month respectively.

image

https://secure.php.net/supported-versions.php

But I expect we'd also want to support 7.1, and should also add 7.1 and 7.2 to `.travis.yml`.

What do others think?

**Comment by zYn** [comment]
Updated a little by removing the composer.lock file.
It has no effect when used as a library and it seems to break the tests for no reason.

**Comment by Jalle19** [comment]
@zYn can you update the Travis CI configuration so it also tests on PHP 7.1 and 7.2? You can remove HHVM from the tests as well.

**Comment by zYn** [comment]
Done

**Comment by Jalle19** [comment]
I merged and tagged 1.1.0, but @crisu83 will have to update Packagist manually (we changed the organization name a year ago and this package hasn't been touched in a while)

**Comment by Jalle19** [comment]
https://packagist.org/packages/nordsoftware/paytrail-php#1.1.0

**Pull request merged**
